### ISSUE TITLE
The routing file "pentatrion_vite.yaml" contains unsupported keys

### ISSUE THREAD

**Issue by WebMechanic** [lhapaipai/vite-bundle#30]
Salût,

after updating to the latest version (2.2.1) with this yaml file according to the readme's "Bundle Configuration"

```yaml
_pentatrion_vite:
    # Base public path when served in development or production
    prefix: /public/build
    # path to the web root relative to the Symfony project root directory
    public_dir: /public
    script_attributes:
        # you can define your attributes that you want to apply
        # for all your script tags
    link_attributes:
        # you can define your attributes that you want to apply
        # for all your link tags
    resource: "@PentatrionViteBundle/Resources/config/routing.yaml"
```
I get an elaborate error message from Symfony or running a composer update

The routing file "D:\...\config/routes/dev/pentatrion_vite.yaml" 
contains unsupported keys for "_pentatrion_vite": `"public_dir", "script_attributes", "link_attributes"`. 
Expected one of: `"resource", "type", "prefix", "path", "host", "schemes", "methods", "defaults", "requirements", "options", "condition", "controller", "name_prefix", "trailing_slash_on_root", "locale", "format", "utf8", "exclude", "stateless"` 
in D:\...\config/routes/dev/pentatrion_vite.yaml 
(which is being imported from "D:\...\src\Kernel.php").

I have to remove all but `prefix` to make it run.

Running `composer recipes pentatrion/vite-bundle` responds with "up to date"

I "discovered" `public_dir` digging through the former release, and adding it also resulted in an error.

à la prochaine

**Comment by lhapaipai** [comment]
hi @WebMechanic ,
these new options were not applied in the correct file

```yaml
# config/packages/pentatrion_vite.yaml
pentatrion_vite:
    script_attributes:
        # you can define your attributes that you want to apply
        # for all your script tags

    link_attributes:
        # you can define your attributes that you want to apply
        # for all your link tags
```

```yaml
# config/routes/dev/pentatrion_vite.yaml
_pentatrion_vite:
    prefix: /build
    resource: "@PentatrionViteBundle/Resources/config/routing.yaml"
```
