### ISSUE TITLE
Relative Assets in SASS aren't resolved correctly

### ISSUE THREAD

**Issue by andyexeter** [lhapaipai/vite-bundle#33]
Hey there,

There seems to be an issue in this bundle and/or its Vite configuration with relative asset paths in SASS.

With a directory structure like this:

```
assets
├── app.js
├── images
│   └── vite.svg
└── styles
    ├── pages
    │   └── home.scss
    └── style.scss

```

And `home.scss` containing this:

```scss
#app {
  width: 410px;
  height: 404px;
  background-image: url('../../images/vite.svg');
}
```

The background image does not load.

However, if you change the background image URL to `../images/vite.svg` then it does load - but this is incorrect because `images/` is 2 levels above `styles/pages`.

This used to be [an issue in Vite itself](https://github.com/vitejs/vite/issues/7651), but was recently [fixed](https://github.com/vitejs/vite/pull/10741) in [v3.2.3](https://github.com/vitejs/vite/blob/v3.2.3/packages/vite/CHANGELOG.md)

I have created two demo projects to help debug this issue:

This is a standard Vite project, showing that the path is resolved correctly: https://stackblitz.com/edit/vitejs-vite-2btrkm

And this is a standard Symfony 6.1 project with this bundle installed: https://github.com/andyexeter/vite-bundle-issue-demo

If you install and run the Symfony project you'll see that the background image does not display unless you change the path to the incorrect one.

**Comment by lhapaipai** [comment]
hi @andyexeter, 
one solution could be to define an alias ?
```js
// vite.config.js
import { resolve } from 'path';


export default defineConfig({
  // ...
  resolve: {
    alias: {
      '~': resolve(__dirname, 'assets'),
    }
  }
})
```

```scss
/* home.scss */
#app {
  width: 410px;
  height: 404px;
  background-image: url('~/images/vite.svg');
}
```

this does not solve the problem but offers an elegant solution ?
