### ISSUE TITLE
Handle multiple builds

### ISSUE THREAD

**Issue by hdasdoria** [lhapaipai/vite-bundle#38]
Hi! 

First of all, thanks for your work and for that very useful bundle! 

With my team, we currently are trying to migrate all our Symfony bases apps from webpack encore to vite, but there is one final point that prevent us from migrating all of them. It's about handling multiple builds in separate build directories, with a manifest.json/entrypoints.json for each one.

Currently, symfony/webpack-encore-bundle provides a solution with this configuration: 
```yaml
webpack_encore:
    # if you have multiple builds:
    builds:
        frontend: '%kernel.project_dir%/public/frontend/build'
```

Used with this twig:
```twig
{{ encore_entry_script_tags('app', null, 'frontend') }}
```

Are there any plans about adding this feature to your bundle, or have you ever thought about that?

Would also be interesting to know if you are looking to provide the "exact" same features as in symfony/webpack-encore or if you just aim to provide a way to use Vite in some SF apps.
