### ISSUE TITLE
My assets are not linked in my twig files in production

### ISSUE THREAD

**Issue by Samy-Belarbi** [lhapaipai/vite-bundle#48]
Hey, **thanks for your great work**. I am currently migrating my app from Webpack-encore to Vite.

My app is using React & Symfony. I followed your instructions, and everything is working perfectly fine in dev server/locally, but i have issues when i am pushing to production in my Review App.

My twig are rendered without any `<script>` or `<link>` from my `vite_entry_..._tag`. I have no idea if that's because it can't find any assets so it doesn't write tags, or if that's because another reason.

My assets are btw uploaded in a CDN, so that's why i am using an env variable.

Do you have any ideas how can i fix that ? Thank you.

Here is my `vite.config.js` :

```js
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd());

  return {
    resolve: {
      alias: {
        // ...
      },
    },
    plugins: [
      react(),
      symfonyPlugin({
        /* defaultValues */
        servePublic: true,
        refresh: true,
        /** If you set server.host: '0.0.0.0' in your vite.config.js
         * you have to set 'localhost' */
        viteDevServerHostname: null,
      }),
    ],
    base: `${env.VITE_ASSET_PATH}/build`,
    build: {
      outDir: './public/build',
      manifest: true,
      rollupOptions: {
        input: {
          // ...
        },
      },
    },
    server: {
      origin: 'http://localhost:5173',
    },
  };
});
```

My `entrypoints.json` look like this : 
```js
  "entryPoints": {
    "example": {
      "js": [
        "https://cdn.example.com/build/assets/example-b5917c32.js"
      ],
      "css": [],
      "preload": [
        "https://cdn.example.com/build/assets/example-c72ab971.js",
```

My `manifest.json` : 
```js
  "Example.css": {
    "file": "assets/Example-09455f0e.css",
    "src": "Example.css"
  },
```

My `pentatrion_vite.yaml` : 
```yaml
# config/packages/pentatrion_vite.yaml
pentatrion_vite:
  # path to the web root relative to the Symfony project root directory
  public_dir: /public

  # Base public path when served in development or production
  base: /build/
```

My `assets.yaml` : 
```yaml
framework:
  assets:
    base_urls:
      - '%env(ASSET_PATH)%'
    json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
```

EDIT : 
"Partially" fixed by changing "build" by an another name, somehow it was getting replaced by something.
