### ISSUE TITLE
Images not copied on build

### ISSUE THREAD

**Issue by 3PSY0N** [lhapaipai/vite-bundle#53]
Hello, I have a strange problem, some images are not copied in the directory `public/build/` and the manifest is not correctly filled.
Some images are well added to the manifest and other images are not added at all.
I use the same method to load images (via `{{ asset() }}`)

My config:

```yaml
# config/packages/framework.yaml

framework:
  assets:
    version_strategy: 'Pentatrion\ViteBundle\Asset\ViteAssetVersionStrategy'
```

```js
// vite.config.js

import { defineConfig } from "vite";
import symfonyPlugin from "vite-plugin-symfony";

export default defineConfig({
    plugins: [
        symfonyPlugin(),
    ],
    build: {
        rollupOptions: {
            input: {
                app: "./assets/js/app.js",
            },
        }
    },
});

```

```js
// assets/js/app.js

import.meta.glob(["../img/**"]);
```

In my base.html.twig
```twig
{% block stylesheets %}
  {{ vite_entry_link_tags('app') }}
{% endblock %}

{% block javascripts %}
  {{ vite_entry_script_tags('app') }}
{% endblock %}
```

in my templates
```twig
<img src="{{ asset('assets/img/image_name.jpg') }}">
```

it's a strange behavior =/

Edit: In dev mode, everything is ok
