### ISSUE TITLE
Images in SASS is not resolved in dev mode

### ISSUE THREAD

**Issue by zendiik** [lhapaipai/vite-bundle#62]
In the scss file I have a url with the path to the image, which vite translates correctly. The problem is that it forgets to add the base url from vite dev mode.

```scss
.logo {
	background-image: url(/assets/images/logo.svg);
}
```

In browser console is:
![image](https://github.com/lhapaipai/vite-bundle/assets/10212768/50637cd1-8873-467e-a94d-d7676c49199f)

But for me, the url has to be this: `https://localhost:5173/build/assets/images/logo.svg`

Am I doing something wrong? Am I configured it wrong?

Thanks for your help.
